model_name: Bean-3B
base_model: openlm-research/open_llama_3b_v2
model_context_window: 2048
data:
  type: vicuna
  dataset: 64bits/lima_vicuna_format
lora:
  r: 8
  lora_alpha: 32
  target_modules:
  - c_attn
  - c_proj
  lora_dropout: 0.10
  bias: none
  task_type: CAUSAL_LM
trainer:
  batch_size: 1
  gradient_accumulation_steps: 1
  warmup_steps: 50
  num_train_epochs: 2
  learning_rate: 0.0002
  logging_steps: 20
trainer_output_dir: trainer_outputs/
model_output_dir: models/
