model_name: Marx-3B-V3
base_model: stabilityai/stablelm-3b-4e1t
model_context_window: 4096
data:
  type: vicuna
  dataset: acrastt/EverythingLM-V3-ShareGPT
lora:
  r: 64
  lora_alpha: 16
  target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - lm_head
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
trainer:
  batch_size: 4
  gradient_accumulation_steps: 4
  warmup_steps: 30
  num_train_epochs: 2
  learning_rate: 0.0001
  logging_steps: 1
trainer_output_dir: trainer_outputs/
model_output_dir: models/
